### ISSUE TITLE
A question and not issue

### ISSUE THREAD

**Issue by cindro** [leastprivilege/AspNet5TemplateCookieAuthentication#1]
Thanks for this great template/sample.

I was able to load the value of Email from a controller, this worked fine. My question: is there a simpler way of getting the same value without using Linq?

var claim = User.Claims.ToList();
ViewData["CurrentEmail"] = claim.Find(r => r.Type == "Email").Value;

**Comment by leastprivilege** [comment]
User.FindFirst("email").Value

**Comment by cindro** [comment]
Wow, how did I not see that....thank you sir.
